import { getSession } from "next-auth/client";
import Head from "next/head";
import React from "react";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";

export default function Home({ session }) {
  console.log(session);
  // if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* main */}
      <main className="flex">
        <Sidebar />
        {/* FEED */}
        {/* WIDGET */}
      </main>
    </div>
  );
}
export async function getServerSideProps(context) {
  // get the user
  const session = await getSession(context);
  return {
    props: { session },
  };
}
